services:
  redis:
    image: redis:alpine
    container_name: qairline-redis
    ports:
      - "6379:6379"
    networks:
      - qairline-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: qairline-postgres
    environment:
      POSTGRES_DB: flight_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: viet12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qairline-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: backend-backend:latest
    container_name: qairline-backend
    ports:
      - "8080:8080"
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_booking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: viet12345

      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # Frontend URL
      APP_FRONTEND_URL: http://localhost:3000

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - qairline-network
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  qairline-network:
    driver: bridge
